### ISSUE TITLE
Rename GeoJSON.d.ts to GeoJson.d

### ISSUE THREAD

**Issue by javisan** [Microsoft/Bing-Maps-V8-TypeScript-Definitions#11]
Hi,

I've tested GeoJson functionality Microsoft.Maps.loadModule("Microsoft.Maps.GeoJson"). As soon as you rename file GeoJSON.d.ts to GeoJson.d (and references inside file JSON -> Json), that works perfectly.

Thanks for your work,
Javi

**Comment by rbrundritt** [comment]
Wasn't sure what you were saying at first, but figured it out. Good catch. I've updated this locally and will check and update the packages next week when I push out the September updates.

**Comment by rbrundritt** [comment]
This has now been fixed and checked in. The npm and Nuget packages have also been updated.
