### ISSUE TITLE
Property 'length' does not exist on type 'Pushpin | Pushpin[]

### ISSUE THREAD

**Issue by javisan** [Microsoft/Bing-Maps-V8-TypeScript-Definitions#12]
Hi, thas message appears with this code:

`var pushpins = Microsoft.Maps.TestDataGenerator.getPushpins(10, this.map.getBounds());
var infobox = new Microsoft.Maps.Infobox(pushpins[0].getLocation(), { visible: false });
infobox.setMap(map);
for (var i = 0; i < pushpins.length; i++) { ... }`

> Property 'length' does not exist on type 'Pushpin | Pushpin[]

Inside Microsoft.Maps.d.ts
Line --> export class Pushpin implements IPrimitive { ...
I have written the property
public length: number;

Now it works, but I supose that isn't the correct way to do it.

**Comment by rbrundritt** [comment]
This is to be expected. The getPushpins function can return an individual pushpin or an array of pushpins. In type script you have to specify the type. When the number of pushpins requests is more than one, an array will be returned. As such you can modify your first line like this:

`var pushpins = <Microsoft.Maps.Pushpin[]>Microsoft.Maps.TestDataGenerator.getPushpins(10, this.map.getBounds());`

**Comment by javisan** [comment]
That's correct. Thank you very much.
