### ISSUE TITLE
Definition output

### ISSUE THREAD

**Issue by wstaelens** [Microsoft/Bing-Maps-V8-TypeScript-Definitions#13]
All my TypeScript outputs are allmost all from DefinitelyTyped.
These definitions install in Scripts/typings.
but MicrosoftMaps installs the definitions in /Scripts.

now it is like this:
```
/
--/Scripts
----/MicrosoftMaps
----/typings
------/bootstrap
------/jquery
------/es6-shim
```

Make it like this!

```
/
--/Scripts
----/typings
------/bootstrap
------/jquery
------/es6-shim
------/MicrosoftMaps
```

When publishing asp.net mvc we only have to take care of one folder "typings".

_P.S.: Move the package over to DefinitelyTyped_

**Comment by rbrundritt** [comment]
This has been discussed previously: https://github.com/Microsoft/Bing-Maps-V8-TypeScript-Definitions/issues/5. These definitions are for Bing Maps V8. Currently the Bing Maps definitions in DefinatelyTyped are for Bing Maps V7. V8 is only 90% backwards compatible, so replacing the definitions in DefinitelyTyped with these new one's will break any application using those definitions for V7. Bing Maps V7 will be retired at the end of June. The plan is to update DefinatelyTyped in May as most devs should be migrating their apps by then.
