### ISSUE TITLE
Directions waypointDisambiguation Unused / Documentation Incorrect

### ISSUE THREAD

**Issue by leebradley** [Microsoft/Bing-Maps-V8-TypeScript-Definitions#14]
It appears there's a problem with the initial directions documentation. `waypointDisambiguation` and `autoDisplayDisambiguation` are referenced, but never actually used in Bing Maps V8.

Initial checkin:
https://github.com/Microsoft/Bing-Maps-V8-TypeScript-Definitions/commit/b767afd7c39d7cc43df2e376939d5869e07f61ac#commitcomment-21954379

New file location:
https://github.com/Microsoft/Bing-Maps-V8-TypeScript-Definitions/blob/master/scripts/MicrosoftMaps/Modules/Directions.d.ts#L129

The migration documentation says disambiguation functionality was removed due to being rarely used (and no longer needed? Although that's confusing because that seems to indicate it's been replaced.)
https://social.technet.microsoft.com/wiki/contents/articles/34563.bing-maps-v7-to-v8-migration-guide.aspx

**Comment by rbrundritt** [comment]
The RouteResponseCode enumerator was in the API, but somehow got marked internal and thus is not currently available. The team is working to correct this. These codes are still valid responses. Note that the disambiguation functionality in V7 wasn't completely deprecated but has transformed significantly and is now handled using auto suggest in V8.
