### ISSUE TITLE
Last 'scripts' folder references to be renamed to the current 'types' folder reference.

### ISSUE THREAD

**Issue by METACEO** [Microsoft/Bing-Maps-V8-TypeScript-Definitions#22]
Although the 'scripts' folder was renamed to 'types' in version 2.x - some references to 'scripts' still exist.

I have opened a [pull request](https://github.com/Microsoft/Bing-Maps-V8-TypeScript-Definitions/pull/21) that [replaces these instances.](https://github.com/Microsoft/Bing-Maps-V8-TypeScript-Definitions/pull/21/files)

**Comment by rbrundritt** [comment]
Yup, saw the pull request. On vacation, but will merge this when I get back. Thanks.

**Comment by rbrundritt** [comment]
Merged

**Comment by METACEO** [comment]
@rbrundritt any idea/estimate as to when the NPM version/package will be updated to included these changes?

**Comment by rbrundritt** [comment]
In the next couple of days, we just had an update to the API, so updating the definitions now.
