### ISSUE TITLE
IMapLoadOptions requires the deprecated field credentials

### ISSUE THREAD

**Issue by AndyCJ** [Microsoft/Bing-Maps-V8-TypeScript-Definitions#26]
https://github.com/Microsoft/Bing-Maps-V8-TypeScript-Definitions/blob/master/types/MicrosoftMaps/Microsoft.Maps.d.ts#L365

    export interface IMapLoadOptions extends IMapOptions, IViewOptions {
        /** The Bing Maps Key used to authenticate the application. This property can only be set when using the Map constructor. */
        credentials: string;
    }

https://msdn.microsoft.com/en-us/library/mt712646.aspx

credentials | string | Deprecated. The Bing Maps Key used to authenticate the application. This property can only be set when using the Map constructor. It is recommended that the Bing Maps key be set as a URL parameter of the Bing Maps script reference as documented in the Setting Map Control Parameters document. This option will continue to work.
-- | -- | --

**Comment by rbrundritt** [comment]
This is to be expected at the moment, the updated typescript definitions for the last release haven't been pushed out yet. The release announcement was last Thursday, the team is working on a number of new API's that are being released and we have Thanksgiving, so updating the typescript definitions has been delayed. That said, I think they are just about ready and will see if I can find an hour today to do this.

**Comment by rbrundritt** [comment]
Version 2.0.1 which includes the November 2017 Updates for V8 has been released and resolves this issue.

**Comment by AndyCJ** [comment]
Thank you.
