### ISSUE TITLE
location property missing from IMouseEventArgs?

### ISSUE THREAD

**Issue by spib** [Microsoft/Bing-Maps-V8-TypeScript-Definitions#29]
The pushpin drag event (https://msdn.microsoft.com/library/mt748664.aspx) should have a location property

            Microsoft.Maps.Events.addHandler(pushpin, "drag", e => {
                this.updatePosition(e.location);
            });

But the typescript compiler complains with

    Property 'location' does not exist on type 'IMouseEventArgs | IPrimitiveChangedEventArgs'.

**Comment by rbrundritt** [comment]
The issue is that two possible event args can be returned by the addHandler function. You need to specify which one is returned. For example:

`this.updatePosition((<Microsoft.Maps.IMouseEventArgs>e).location);`

**Comment by rbrundritt** [comment]
You can also do this:

```
Microsoft.Maps.Events.addHandler(pin, "drag", (e: Microsoft.Maps.IMouseEventArgs) => {
    this.updatePosition(e.location);
});
```

**Comment by spib** [comment]
Ahh, OK thanks for the clarification
