### ISSUE TITLE
`typings` field points to wrong place

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/Bing-Maps-V8-TypeScript-Definitions#31]
The `package.json` contains: `typings": "Microsoft.Maps.All.d.ts",`.
But the typings are actually in in `types/Microsoft.Maps.All.d.ts`.
This means that installing the package and adding `/// <reference types="bingmaps" />` results in a compile error since TypeScript can't find the typings.
Fixing this would enable us to remove the duplicate declarations from DefinitelyTyped and defer to this package.

**Comment by rbrundritt** [comment]
I'll update this in the next update in January.
