### ISSUE TITLE
How would you select language?

### ISSUE THREAD

**Issue by darewreck54** [microsoft/Bing-Maps-V8-TypeScript-Definitions#33]
Hi,

I was wondering how you would configure the language when you initialize the map.  I'm wondering if this is supported or if there is plans to support it.

https://stackoverflow.com/questions/39343024/set-map-language-with-bing-maps-javascript-v8-api

var map = new Microsoft.Maps.Map(document.getElementById('myMap'), {
    /* No need to set credentials if already passed in URL */
    center: new Microsoft.Maps.Location(51.50632, -0.12714),
    mapTypeId: Microsoft.Maps.MapTypeId.aerial,
    zoom: 10 });

Thanks,
Derek

**Comment by IoTGirl** [comment]
Take a look at the "Map" section of [https://bingmapsv8samples.azurewebsites.net/#Localize%20the%20Map%20(fr-FR)](https://bingmapsv8samples.azurewebsites.net/#Localize%20the%20Map%20(fr-FR))
