### ISSUE TITLE
IModuleOptions errorCallback type doesn't match documentation

### ISSUE THREAD

**Issue by jordan-schneider** [microsoft/Bing-Maps-V8-TypeScript-Definitions#34]
In the [documentation for ModuleOptions](https://msdn.microsoft.com/en-us/library/mt712651.aspx) it says that errorCallback's type is function(errorMessage:string): void, but in [this library](https://github.com/Microsoft/Bing-Maps-V8-TypeScript-Definitions/blob/master/types/MicrosoftMaps/Microsoft.Maps.d.ts#L576) it's type is () => void. Which is correct?

**Comment by drwestco** [comment]
The documentation is correct.

```javascript
Microsoft.Maps.loadModule('Dennis', { errorCallback: function (msg) { alert(msg) } });
```
```
> Dennis is not a supported module.
```

**Comment by improving-jeffd** [comment]
Thanks for merging in that pull request! Do you know when this will release to npm? Not sure what the repo's setup is for publishing updates.

**Comment by rbrundritt** [comment]
Not sure if or when it will be merged into NPM. I moved off the Bing Maps team 4 years ago and have been focused on growing the Azure Maps platform.
