### ISSUE TITLE
TypeScript Error - Cannot find name Microsoft

### ISSUE THREAD

**Issue by nsankaranarayanan** [microsoft/Bing-Maps-V8-TypeScript-Definitions#36]
I followed the instructions provided in the website https://github.com/Microsoft/Bing-Maps-V8-TypeScript-Definitions . My Visual Studio Code is not showing any errors though I get the error "Cannot find name Microsoft" when I try to run my angular project.

I tried both methods and still get the below error.
- Install npm package
- Use DefinitelyTyped

I also tried to include the bingmaps in the package.json and that didn't work either.
Can someone please tell me what I am doing wrong?

**Error**: 
> error TS2304: Cannot find name 'Microsoft'.

**Below is my code sample** 
```
var options = {maxResults: 5, businessSuggestions: true};
Microsoft.Maps.loadModule('Microsoft.Maps.AutoSuggest', function () {
var manager = new Microsoft.Maps.AutosuggestManager( options );
manager.attachAutosuggest('#searchBox', '#searchBoxContainer', suggestionSelected);
});

```
**First attempt**
```
/// <reference path="../../../../../../node_modules/bingmaps/types/MicrosoftMaps/CustomMapStyles.d.ts" />
/// <reference path="../../../../../../node_modules/bingmaps/types/MicrosoftMaps/Microsoft.Maps.d.ts" />
/// <reference path="../../../../../../node_modules/bingmaps/types/MicrosoftMaps/Modules/Autosuggest.d.ts" />
```

**Second attempt**
```
/// <reference path="../../../../../../node_modules/@types/bingmaps/index.d.ts" />
/// <reference path="../../../../../../node_modules/@types/bingmaps/Autosuggest.d.ts" />
/// <reference path="../../../../../../node_modules/@types/bingmaps/Clustering.d.ts" />
```

### Environment Info
**OS**: Windows 10
**Browser**: Chrome 69.0.3497.92 (Official Build) (64-bit)
**Angular**: 5.1.0
**TypeScript**: 2.4.2

**Comment by rbrundritt** [comment]
Have you added a URL that points to the actual api? These are only definitions, not the actual api

**Comment by nsankaranarayanan** [comment]
@rbrundritt Are you referring to the below code? If yes then yes. I have already added that to my index.html.

`<script type='text/javascript' src='https://www.bing.com/api/maps/mapcontrol?callback=GetMap&key=[Your_Bing_Maps_Key]' async defer></script>
`

**Comment by rbrundritt** [comment]
Yes. Is your code trying 5o access the Microsoft names pace before the GetMap function is called, if so then you 2ould get the error you mentioned.

**Comment by nsankaranarayanan** [comment]
@rbrundritt The error I am referring to is not at runtime. It is when I try to startup the application (ng serve).

**Comment by rbrundritt** [comment]
Angular might require you to use import instead of reference tags.

**Comment by nsankaranarayanan** [comment]
I tried to import but could not get the proper location / name.
Could you please show me how to do this @rbrundritt ?

**Comment by maximreynaud** [comment]
Hello @nsankaranarayanan,

Did you success import in your project ?
I try to import it in SPFX project (ReactJs / typeScript) .

**Comment by isabellachen** [comment]
I think problem is Microsoft object is attached to window.
https://stackoverflow.com/questions/53153725/how-can-i-use-bing-maps-loaded-from-external-cdn-inside-my-vuejs-application

**Comment by IoTGirl** [comment]
This was answered in the forums at [https://social.msdn.microsoft.com/Forums/en-US/61e646bc-1d56-4865-9f55-099737798940/angular-4-bing-maps-v8-web-controls-setup-issue](https://social.msdn.microsoft.com/Forums/en-US/61e646bc-1d56-4865-9f55-099737798940/angular-4-bing-maps-v8-web-controls-setup-issue)

>The component was trying to load the Microsoft api before it had fully been loaded. I ended up adding a listener to document.ready to load that component once the state was complete
