### ISSUE TITLE
Cannot import types into project

### ISSUE THREAD

**Issue by isabellachen** [microsoft/Bing-Maps-V8-TypeScript-Definitions#38]
Am working on Typescript project and having trouble importing the bingmap types. I try to import the types like so:
```js
import { Location } from 'bingmaps'
import * as all from 'bingmaps'
import { Microsoft } from 'bingmaps'
```
I didn't try to import them all at the same time. These are just three ways I tried to import. In anycase I don't think the way I try to import them is the problem. 

My compiler keeps complaining node_modules/bingmaps/types/MicrosoftMaps/Microsoft.Maps.all.d.ts is not a module. 

Looking into node_modules/bingmaps folder, there are files.

I have the script and my map is working as expected. There must be some way to import the type definitions in my project... this surely should be documented somewhere. Can someone help?

**Comment by perfahlen** [comment]
reference them, top of your ts file

/// <reference path="types/MicrosoftMaps/Microsoft.Maps.d.ts" />

**Comment by PhanTien** [comment]
I have the same problem. Can anyone help, please?

**Comment by SamuelQZQ** [comment]
The definition file is not written as a module. I can modify it. But I don't know if it's acceptable or not by the Bing Maps team. 

@rbrundritt

**Comment by IoTGirl** [comment]
@rbrundritt  This is still supported by the Bing Maps team.  I will reach out to them with a link to this issue.

**Comment by SamuelQZQ** [comment]
I found that it's may because of we can only get the implementation JavaScript file of Bing map on runtime or through HTML <script> tag.

We can not use import syntax when don't have the implementation file locally. So, until now the `reference` syntax maybe the only method to use the Bing map. 

Wish Bing map team can give some solutions. The Bing map APIs are developed so well. It's a pity to give up using it because of legacy reference usage.

**Comment by ncausey** [comment]
Not sure if this would still be of help, but I am able to simply do `import 'bingmaps';` in my TS file, and it adds a global reference to the Microsoft namespace.

Then I can use it as expected: `new Microsoft.Maps.Map`, `new Microsoft.Maps.Infobox`, etc.

**Comment by rdhainaut** [comment]
> Not sure if this would still be of help, but I am able to simply do `import 'bingmaps';` in my TS file, and it adds a global reference to the Microsoft namespace.
> 
> Then I can use it as expected: `new Microsoft.Maps.Map`, `new Microsoft.Maps.Infobox`, etc.

You save my day :) Thank you !
