### ISSUE TITLE
Changing the view from Road to Aerial, Javascript Error

### ISSUE THREAD

**Issue by pandillaanil** [Microsoft/Bing-Maps-V8-TypeScript-Definitions#39]
We are using TypeScript definitions package for the Bing Maps V8 Web Control in our React application.

While changing the view from Road to Aerial, we are getting the below error.

![image](https://user-images.githubusercontent.com/46781296/51315180-8ff2df80-1a77-11e9-90f7-710b0d8a3618.png)

Please refer this url for more details
https://social.msdn.microsoft.com/Forums/en-US/2052b8db-8e85-4d7f-bb02-760a32c7725a/bing-maps-v8-typescript-definitions-javascript-error?forum=bingmapsajax

**Comment by zhangyiatmicrosoft** [comment]
Can you share more code context?
In Microsoft.Maps.d.ts: the definition is actually lower case "aerial" and "road", not Aerial.

**Comment by pandillaanil** [comment]
/// <reference path="../../microsoftmaps/microsoft.maps.all.d.ts" />
import * as React from 'react';
import $ from 'jquery';
var Config: RcWeb.ConfigDto = require('Config');
import * as MapCallouts from './../components/childcomponents/BingMapCallouts';
import { RCUtils } from './../RCUtils';
import { ReeferStatusGrid } from '../components/childcomponents/ReeferStatusGrid';
var pinInfobox = null;
var reeferMap = null;
var layer = null;
var PushpinsData = [];
var gridName = null;
var calloutState = true;

class ReeferCallout {
    static InitializeMap(params: any) {
        reeferMap = new Microsoft.Maps.Map(document.getElementById(params), {
            credentials: Config.BingMapsKey,
            mapTypeId: Microsoft.Maps.MapTypeId.road,
            zoom: 4,
            showMapTypeSelector: true,
            disableKeyboardInput: true,
            liteMode: true
        });

        //var bounds = Microsoft.Maps.LocationRect.fromCorners(new Microsoft.Maps.Location(40.5, -123.5), new Microsoft.Maps.Location(40, -123));
        //var overlay = new PanningOverlay(bounds);
        //reeferMap.layers.insert(overlay);       
      
    }
    static ResetMapPushpins() {
        if (layer != null) {
            if (pinInfobox != null){                
                pinInfobox.setOptions({ visible: false });
                pinInfobox.setMap(null);
            }                
            layer.clear();
        }
        calloutState = true;
    }
    static ResetCalloutState(){
        calloutState = true;
    }
    static BindClusterMapPushpins(selectedRows: any, gridType: string) {
        PushpinsData = [];
        PushpinsData = selectedRows;
        gridName = gridType;
        Microsoft.Maps.loadModule('Microsoft.Maps.Clustering', { callback: clusterReeferModuleLoaded });
    }    
    static BindTracePushpins(selectedRows: any, gridType: string) {
        gridName = gridType;
        PushpinsData = [];
        if (layer != null) {
            if (pinInfobox != null)
                pinInfobox.setOptions({ visible: false });
            layer.clear();
        }
        layer = new Microsoft.Maps.Layer();
        $.each(selectedRows, function (selectedIndex, selectedValue) {
            if (selectedValue.GPSLatitude != null && selectedValue.GPSLongitude != null) {
                var latitude = selectedValue.GPSLatitude;
                var longitude = selectedValue.GPSLongitude;
                
                var imageSource = '';
                if (selectedValue.GPSLatitude != 0 && selectedValue.GPSLongitude != 0 && ((selectedValue.GPSLockState == null || selectedValue.GPSLockState == "") || selectedValue.GPSLockState.toString().toUpperCase() != "LOCKED"))
                 imageSource =  'pushpin_gray.png';
                else if (parseInt(selectedIndex) == 0)
                  imageSource =  'pushpin_yellow.png';
                else if (parseInt(selectedIndex) == parseInt(selectedRows.length) - 1)
                  imageSource =  'pushpin_blue.png';
                else if (selectedValue.EventMasterID.toString() == "57")
                  imageSource =  'pushpin_green.png';
                else if (selectedValue.EventMasterID.toString() == "58")
                  imageSource =  'pushpin_red.png';
                else
                  imageSource =  'pushpin_gray.png';

                var pushpinImage = require('../../wwwroot/images/MapPushPins/'+ imageSource +'');
                var pushpinOptions = { icon: pushpinImage, height: 31, width: 20, anchor: new Microsoft.Maps.Point(11, 8) };
                var center = new Microsoft.Maps.Location(latitude, longitude); //reeferMap.getCenter();
                var pushpin = new Microsoft.Maps.Pushpin(center, pushpinOptions);
                if (gridType == "status")
                    pushpin.setOptions({ color: selectedValue.UnitMasterID });
                else
                    pushpin.setOptions({ color: selectedValue.ParentEventID });
                /* InfoBox Code Starts */            
                //pushpin.Description = '<div id=' + selectedValue.UnitMasterID + ' style="margin-top:-10px;font-size: xx-small;color: #666;"></div>';
                // Create the infobox for the pushpin
                pinInfobox = new Microsoft.Maps.Infobox(pushpin.getLocation(), {
                    visible: false
                });
                pinInfobox.setMap(reeferMap);
                // Add handler for the pushpin click event.
                Microsoft.Maps.Events.addHandler(pushpin, 'mouseover', function (args) { displayReeferInfobox(args, gridType); });
                Microsoft.Maps.Events.addHandler(pushpin, 'click', function (args) { displayReeferInfoboxOnClick(args, gridName); });
                //Microsoft.Maps.Events.addHandler(pushpin, 'click', function (args) { displayReeferInfobox(args) });
                // Hide the infobox when the map is moved.
                //Microsoft.Maps.Events.addHandler(pushpin, 'mouseout', function (args) { hideReeferInfobox(args) });
                /* InfoBox Code end     */
                layer.add(pushpin);
                PushpinsData.push(selectedValue);
            }
        });
        reeferMap.layers.insert(layer);
        reeferMap.setView({ zoom: 10 });
        $('#globalLoader').hide();
        //reeferMap.entities.push(pushpin);
    }
    static DisplaySelectedPushpin(selectedRow: any) {
        calloutState = false;
        if (selectedRow.GPSLatitude != null && selectedRow.GPSLongitude != null) {
            if (pinInfobox != null){
                pinInfobox.setOptions({ visible: false });
                pinInfobox.setMap(null);
            }

            var latitude = selectedRow.GPSLatitude;
            var longitude = selectedRow.GPSLongitude;

            var rowIndex = 0;
            $.each(PushpinsData, function (index, value) {
                if (value.ParentEventID == selectedRow.ParentEventID) {
                    rowIndex = index;
                    return false;
                }
            });
            var imageSource = '';
           
            if (selectedRow.GPSLatitude != 0 && selectedRow.GPSLongitude != 0 && ((selectedRow.GPSLockState == null || selectedRow.GPSLockState == "") || selectedRow.GPSLockState.toString().toUpperCase() != "LOCKED"))
                imageSource = 'pushpin_gray.png';
            else if (rowIndex == 0)
                imageSource = 'pushpin_yellow.png';
            else if (rowIndex == PushpinsData.length - 1)
                imageSource = 'pushpin_blue.png';
            else if (selectedRow.EventMasterID.toString() == "57")
                imageSource = 'pushpin_green.png';
            else if (selectedRow.EventMasterID.toString() == "58")
                imageSource = 'pushpin_red.png';
            else
                imageSource = 'pushpin_gray.png';
           

            var pushpinImage = require('../../wwwroot/images/MapPushPins/' + imageSource + '');
            var popOffset = new Microsoft.Maps.Point(-4, 160);
            //var pushpinImage = require('../../wwwroot/images/bingcenterSelected_icon.png');
            var pushpinOptions = { icon: pushpinImage, height: 31, width: 20, anchor: new Microsoft.Maps.Point(11, 8) };
            var latLong = new Microsoft.Maps.Location(latitude, longitude); //reeferHistoryMap.getCenter();
            var pushpin = new Microsoft.Maps.Pushpin(latLong, pushpinOptions);
            if (gridName == "status")
                pushpin.setOptions({ color: selectedRow.UnitMasterID });
            else
                pushpin.setOptions({ color: selectedRow.ParentEventID });

            var identityCode = GenerateAlphaNumericCode(6);
            /* InfoBox Code Starts     */
            var description = '<div id=' + identityCode + ' class="tab-infobox"></div>';
            var DescElement = React.createElement(MapCallouts.PinInfoboxDescription, { selectedPin: selectedRow, divid: identityCode });
            RCUtils.RenderChildComponent(identityCode, DescElement);
            // Create the infobox for the pushpin
            pinInfobox = new Microsoft.Maps.Infobox(latLong, {
                maxHeight: 200,
                maxWidth: 540,
                showPointer: true,
                description: description,
                offset: popOffset,
                showCloseButton: true
            });
            reeferMap.setView({
                center: latLong,
                mapTypeId: Microsoft.Maps.MapTypeId.road
            });

            pinInfobox.setMap(reeferMap);

            Microsoft.Maps.Events.addHandler(pushpin, 'mouseover', function (args) { displayReeferInfobox(args, gridName); });
            Microsoft.Maps.Events.addHandler(pushpin, 'click', function (args) { displayReeferInfoboxOnClick(args, gridName); });
            debugger;
            layer.remove(pushpin);
            layer.add(pushpin, 0); // adding selected row to layer object at index 0
            reeferMap.layers.insert(layer);

        }
        else {
            if (pinInfobox != null) {
                pinInfobox.setOptions({ visible: false });
                pinInfobox.setMap(null);
            }
            var identityCode = GenerateAlphaNumericCode(6);
            var popOffset = new Microsoft.Maps.Point(-120, 100);
            /* InfoBox Code Starts     */
            var description = '<div id=' + identityCode + ' class="tab-infobox"></div>';
            var htmlElement = React.createElement(MapCallouts.PinInfoboxNoLocation, { selectedPin: null, divid: identityCode });
            RCUtils.RenderChildComponent(identityCode, htmlElement);
           /* InfoBox Code Ends     */
            var center = reeferMap.getCenter();            
            pinInfobox = new Microsoft.Maps.Infobox(center, {
                htmlContent: description,
                offset: popOffset,
                maxHeight: 100,
                maxWidth: 340
            });
            reeferMap.setView({
                center: center,
                mapTypeId: Microsoft.Maps.MapTypeId.road
            });
            pinInfobox.setMap(reeferMap);
           
        }
    }
}

//class PanningOverlay extends Microsoft.Maps.CustomOverlay {
//    bounds: Microsoft.Maps.LocationRect;
//    private panUpBtn: HTMLInputElement;
//    private panDownBtn: HTMLInputElement;
//    private panLeftBtn: HTMLInputElement;
//    private panRightBtn: HTMLInputElement;

//    constructor(bounds: Microsoft.Maps.LocationRect) {
//        super({ beneathLabels: false });
//        this.bounds = bounds;
        
//        this.panUpBtn = document.createElement('input');
//        this.panUpBtn.type = 'button';
//        this.panUpBtn.value = '˄';
//        this.panUpBtn.onclick = () => {
//            this.panMap('up');
//        };
//        this.panDownBtn = document.createElement('input');
//        this.panDownBtn.type = 'button';
//        this.panDownBtn.value = '˅';
//        this.panDownBtn.onclick = () => {
//            this.panMap('down');
//        };
//        this.panLeftBtn = document.createElement('input');
//        this.panLeftBtn.type = 'button';
//        this.panLeftBtn.value = '<';
//        this.panLeftBtn.onclick = () => {
//            this.panMap('left');
//        };
//        this.panRightBtn = document.createElement('input');
//        this.panRightBtn.type = 'button';
//        this.panRightBtn.value = '>';
//        this.panRightBtn.onclick = () => {
//            this.panMap('right');
//        };

//    }
//    onAdd() {
//        var container = document.createElement('div');
//        container.appendChild(this.panUpBtn);
//        container.appendChild(this.panDownBtn);
//        container.appendChild(this.panLeftBtn);
//        container.appendChild(this.panRightBtn);
//        container.style.position = 'absolute';
//        container.style.top = '10px';
//        container.style.left = '10px';
//        this.setHtmlElement(container);
//    }
//    panMap(dir: any) {
//        var dx = 0, dy = 0;
//        switch (dir) {
//            case 'up':
//                dy = -30;
//                break;
//            case 'down':
//                dy = 30;
//                break;
//            case 'left':
//                dx = -30;
//                break;
//            case 'right':
//                dx = 30;
//                break;
//        }
//        var cp = reeferMap.tryLocationToPixel(reeferMap.getCenter());
//        cp.x += dx;
//        cp.y += dy;
//        reeferMap.setView({ center: reeferMap.tryPixelToLocation(cp) });
//    }
//}
function clusterReeferModuleLoaded() {
    //Create an infobox at the center of the map but don't show it.
    pinInfobox = new Microsoft.Maps.Infobox(reeferMap.getCenter(), {
        visible: false
    });
    //Assign the infobox to a map instance.
    pinInfobox.setMap(reeferMap);

    if (layer != null)
        layer.clear();

    var reeferPushpins = [];
    var firstLatitude;
    var firstLongitude;
    var count = 0;
    for (var i = 0; i < PushpinsData.length; i++) {
        if (PushpinsData[i].GPSLatitude != null && PushpinsData[i].GPSLatitude != null) {
            var pushpinImage;
            var colorId;
            if (gridName == "status"){
                pushpinImage = require('../../wwwroot/images/dry_normal.png');
                colorId = PushpinsData[i].UnitMasterID;
            }
            else {
                pushpinImage = require('../../wwwroot/images/history_normal.png'); 
                colorId = PushpinsData[i].ParentEventID;
            }
            if(count == 0)
            {
                firstLatitude = PushpinsData[i].GPSLatitude;
                firstLongitude = PushpinsData[i].GPSLongitude;
            }
            count++;
            var pushpinOptions = { icon: pushpinImage, height: 31, width: 20, anchor: new Microsoft.Maps.Point(11, 8) };
            var latitude = PushpinsData[i].GPSLatitude;
            var longitude = PushpinsData[i].GPSLongitude;
           
            var latLon = new Microsoft.Maps.Location(latitude, longitude);

            var pushpin = new Microsoft.Maps.Pushpin(latLon, pushpinOptions);
           
            pushpin.setOptions({ color: colorId });

            //Microsoft.Maps.Events.addHandler(pin, 'click', function (args) { MainMapdisplayInfoboxSelect(args); });
            Microsoft.Maps.Events.addHandler(pushpin, 'mouseover', function (args) { displayReeferInfobox(args, gridName); });
            Microsoft.Maps.Events.addHandler(pushpin, 'click', function (args) { displayReeferInfoboxOnClick(args, gridName); });
            //Microsoft.Maps.Events.addHandler(pin, 'mouseout', function (args) { MainMaphideInfoboxNew(args); });

            reeferPushpins.push(pushpin);

        }       
         
    }

    layer = new Microsoft.Maps.ClusterLayer(reeferPushpins, {
        clusteredPinCallback: function (cluster) {
            //Customize clustered pushpin.             
            var minRadius = 8;
            var outlineWidth = 1;
            var fillColor;            
            if (gridName == "status")
                fillColor = 'rgba(0, 176, 70, 1)';//'rgba(0, 0, 0, 1)';
            else
                fillColor = 'rgba(253, 120, 0, 1)';
            var fillColorDefault = 'rgba(255, 255, 255, 1)';
            var lstClusterPins = [];

            var strPinCount = cluster.containedPushpins.length.toString();
            var strlen = strPinCount.length > 4 ? 4 : strPinCount.length;
            //for (var i = 0; i < cluster.containedPushpins.length; i++) {
            //    var eventId = cluster.containedPushpins[i].getColor();                
            //    var clusterItem = {
            //        EventId: eventId
            //    };
            //    lstClusterPins.push(clusterItem);
            //}
            var clusterSize = cluster.containedPushpins.length;
            var radius = Math.log(clusterSize) / Math.log(10) * 3 + minRadius;

            //Create an SVG string of two circles, one on top of the other, with the specified radius and color.
            var svg = ['<svg xmlns="http://www.w3.org/2000/svg" width="', (radius * 2), '" height="', (radius * 2), '">',
                '<circle cx="', radius, '" cy="', radius, '" r="', radius, '" fill="', fillColorDefault, '"/>',
                '<circle cx="', radius, '" cy="', radius, '" r="', radius - outlineWidth, '" fill="', fillColor, '"/>',
                '</svg>'];
            //Customize the clustered pushpin using the generated SVG and anchor on its center.
            cluster.setOptions({
                icon: svg.join(''),
                anchor: new Microsoft.Maps.Point(radius, radius),
                textOffset: new Microsoft.Maps.Point(0, radius - 8), //Subtract 8 to compensate for height of text.
                //anchor: new Microsoft.Maps.Point(14, 14)
            });
            Microsoft.Maps.Events.addHandler(cluster, 'click', function (args) { clusterPushpinClicked(args); });            
            //var clusterlink = "ShowDeviceClusterPinsData('" + JSON.stringify(lstClusterPins) + "')";
            //cluster.Description = "<div style='width:100px;'><a href='#' onclick=" + clusterlink + ">Limit devices…</a></div>";

            //Microsoft.Maps.Events.addHandler(cluster, 'click', function (args) { ReeferClusterPinsDisplayInfobox(args, clusterlink); });
        },
        gridSize: 80
    });

    reeferMap.layers.insert(layer);
    if(firstLatitude != undefined && firstLongitude != undefined){
        reeferMap.setView({
            center: new Microsoft.Maps.Location(firstLatitude, firstLongitude),
            zoom: 4
        });
    }

}

function clusterPushpinClicked(e) {
    //Check to see if the clicked pushpin has any contained pushpins (this would be a cluster).
    if (e.target.containedPushpins) {
        var locs = [];
        for (var i = 0, len = e.target.containedPushpins.length; i < len; i++) {
            //Get the location of each pushpin.
            locs.push(e.target.containedPushpins[i].getLocation());
        }
        //Create a bounding box for the pushpins.
        var bounds = Microsoft.Maps.LocationRect.fromLocations(locs);
        //Zoom into the bounding box of the cluster. 
        //Add a padding to compensate for the pixel area of the pushpins.
        reeferMap.setView({ bounds: bounds, padding: 100 });
    }
}

function ReeferClusterPinsDisplayInfobox(event, clusterlink) {    
    window.event.cancelBubble = true
    if (!event) var e = window.event
    e.cancelBubble = true;
    if (e.stopPropagation)
        e.stopPropagation();

    if (event.targetType == 'pushpin') {
        try {
            var description = "<div style='width:100px;'><a href='#' onclick=" + clusterlink + ">Limit reefers…</a></div>";
            pinInfobox.setOptions({
                location: event.target.getLocation(),
                showPointer: true,
                description: description,
                showCloseButton: true,
                visible: true,
                offset: new Microsoft.Maps.Point(3, 10),
                maxHeight: 50,
                maxWidth: 150
            });
           
            Microsoft.Maps.Events.addHandler(pinInfobox, 'click', hideReeferInfobox);

        } catch (ex) {
            //alert(ex.message + " " + ex.description);
        }
    } 
}

function displayReeferInfoboxOnClick(event, source) {
    if (event.targetType == 'pushpin') {
        try {
            //var index1 = e.target.Description.indexOf("id=") + 3;
            //var index2 = e.target.Description.indexOf("style") - 1;
            //var unitMasterId = e.target.Description.substring(index1, index2);
            var eventId = event.target._options.color;
            var dataItem = null;
            if (source == "status") {
                for (var i = 0; i < PushpinsData.length; i++) {
                    if (PushpinsData[i].UnitMasterID.toString() == eventId) {
                        dataItem = PushpinsData[i];
                        break;
                    }
                }
            }
            else {
                for (var i = 0; i < PushpinsData.length; i++) {
                    if (PushpinsData[i].ParentEventID.toString() == eventId) {
                        dataItem = PushpinsData[i];
                        break;
                    }
                }
            }
            if (pinInfobox != null) {
                pinInfobox.setOptions({ visible: false });
            }
            var popOffset = new Microsoft.Maps.Point(-4, 165);
             var identityCode = GenerateAlphaNumericCode(6);
            /* InfoBox Code Starts     */
            var description = '<div id='+ identityCode +' class="tab-infobox"></div>';
            var DescElement = React.createElement(MapCallouts.PinInfoboxDescription, { selectedPin: dataItem, divid: identityCode });
            RCUtils.RenderChildComponent(identityCode, DescElement);

            ReeferStatusGrid.SelectCurrentReefer(dataItem);
            // Create the infobox for the pushpin
            pinInfobox.setOptions({
                maxHeight: 200,
                maxWidth: 540,
                showPointer: true,
                description: description,
                location: event.target.getLocation(),
                visible: true, offset: popOffset,
                showCloseButton: true
            });
            
            //#### A buffer limit to use to specify the infobox must be away from the edges of the map.
            var buffer = 30;
            var infoboxOffset = pinInfobox.getOffset();
            var infoboxAnchor = pinInfobox.getAnchor();
            var infoboxLocation = reeferMap.tryLocationToPixel(event.target.getLocation(), Microsoft.Maps.PixelReference.control);
            var dx = infoboxLocation.x + infoboxOffset.x - infoboxAnchor.x;
            var dy = infoboxLocation.y - 20 - infoboxAnchor.y;
            if (dy < buffer) {
                //#### Offset in opposite direction.
                dy *= -1;
                //#### add buffer from the top edge of the map.
                dy += buffer;
            }
            else {
                //#### If dy is greater than zero than it does not overlap.
                dy = 0;
            }
            if (dx < buffer) {
                //#### Offset in opposite direction.
                dx *= -1;
                //#### add a buffer from the left edge of the map.
                dx += buffer;
            }
            else {
                dx = reeferMap.getWidth() - infoboxLocation.x + infoboxAnchor.x - pinInfobox.getWidth();
                //#### If dx is greater than zero then it does not overlap.
                if (dx > buffer) {
                    dx = 0;
                }
                else {
                    //#### add a buffer from the right edge of the map.
                    dx -= buffer;
                }
            }
            //#### Adjust the map so infobox is in view
            if (dx != 0 || dy != 0) {
                //map.setView({
                //    centerOffset: new Microsoft.Maps.Point(dx, dy),
                //    center: map.getCenter()
                //});
                var cp = reeferMap.tryLocationToPixel(reeferMap.getCenter(), Microsoft.Maps.PixelReference.control);
                cp.x -= dx;
                cp.y -= dy;
                reeferMap.setView({ center: reeferMap.tryPixelToLocation(cp, Microsoft.Maps.PixelReference.control) });
            }
        }
        catch (ex) {
            //alert(ex.message + " " + ex.description);
        }
    }
}
function displayReeferInfobox(event, source) {
    if(calloutState) {
        calloutState = false;
        if (event.targetType == 'pushpin') {
            try {
                //var index1 = e.target.Description.indexOf("id=") + 3;
                //var index2 = e.target.Description.indexOf("style") - 1;
                //var unitMasterId = e.target.Description.substring(index1, index2);
                var eventId = event.target._options.color;
                var dataItem = null;
                if (source == "status") {
                    for (var i = 0; i < PushpinsData.length; i++) {
                        if (PushpinsData[i].UnitMasterID.toString() == eventId) {
                            dataItem = PushpinsData[i];
                            break;
                        }
                    }
                }
                else {
                    for (var i = 0; i < PushpinsData.length; i++) {
                        if (PushpinsData[i].ParentEventID.toString() == eventId) {
                            dataItem = PushpinsData[i];
                            break;
                        }
                    }
                }
                if (pinInfobox != null) {
                    pinInfobox.setOptions({ visible: false });
                }
                var popOffset = new Microsoft.Maps.Point(-4, 165);
                 var identityCode = GenerateAlphaNumericCode(6);
                /* InfoBox Code Starts     */
                var description = '<div id='+ identityCode +' class="tab-infobox"></div>';
                var DescElement = React.createElement(MapCallouts.PinInfoboxDescription, { selectedPin: dataItem, divid: identityCode });
                RCUtils.RenderChildComponent(identityCode, DescElement);

                // Create the infobox for the pushpin
                pinInfobox.setOptions({
                    maxHeight: 200,
                    maxWidth: 540,
                    showPointer: true,
                    description: description,
                    location: event.target.getLocation(),
                    visible: true, offset: popOffset,
                    showCloseButton: true
                });
            
                //#### A buffer limit to use to specify the infobox must be away from the edges of the map.
                var buffer = 30;
                var infoboxOffset = pinInfobox.getOffset();
                var infoboxAnchor = pinInfobox.getAnchor();
                var infoboxLocation = reeferMap.tryLocationToPixel(event.target.getLocation(), Microsoft.Maps.PixelReference.control);
                var dx = infoboxLocation.x + infoboxOffset.x - infoboxAnchor.x;
                var dy = infoboxLocation.y - 20 - infoboxAnchor.y;
                if (dy < buffer) {
                    //#### Offset in opposite direction.
                    dy *= -1;
                    //#### add buffer from the top edge of the map.
                    dy += buffer;
                }
                else {
                    //#### If dy is greater than zero than it does not overlap.
                    dy = 0;
                }
                if (dx < buffer) {
                    //#### Offset in opposite direction.
                    dx *= -1;
                    //#### add a buffer from the left edge of the map.
                    dx += buffer;
                }
                else {
                    dx = reeferMap.getWidth() - infoboxLocation.x + infoboxAnchor.x - pinInfobox.getWidth();
                    //#### If dx is greater than zero then it does not overlap.
                    if (dx > buffer) {
                        dx = 0;
                    }
                    else {
                        //#### add a buffer from the right edge of the map.
                        dx -= buffer;
                    }
                }
                //#### Adjust the map so infobox is in view
                if (dx != 0 || dy != 0) {
                    //map.setView({
                    //    centerOffset: new Microsoft.Maps.Point(dx, dy),
                    //    center: map.getCenter()
                    //});
                    var cp = reeferMap.tryLocationToPixel(reeferMap.getCenter(), Microsoft.Maps.PixelReference.control);
                    cp.x -= dx;
                    cp.y -= dy;
                    reeferMap.setView({ center: reeferMap.tryPixelToLocation(cp, Microsoft.Maps.PixelReference.control) });
                }
            }
            catch (ex) {
                //alert(ex.message + " " + ex.description);
            }
        }
    }
}

function hideReeferInfobox(e) {
    if (pinInfobox != null)
        pinInfobox.setOptions({ visible: false });
}

function GenerateAlphaNumericCode(length) {
    var chars = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ',
        result = ""
    for (var i = length; i > 0; --i)
        result += chars[Math.round(Math.random() * (chars.length - 1))]
    return result
}

export default ReeferCallout;

**Comment by zhangyiatmicrosoft** [comment]
Line 19, 170, 204 are all correct (Microsoft.Maps.MapTypeId.road), and when switch, they need to be aerial, just like this page:
https://www.bing.com/api/maps/sdk/mapcontrol/isdk/setmapviewoptions

TS definitions do not really matter at run time.

**Comment by pandillaanil** [comment]
Hi,

The problem is while reloading the cluster pushpins on the map and changing the view from road to aerial, we are getting the script error and pushpins were disappeared on the map.

Calling the BindClusterMapPushpins() method for reloading the map pushpins data.

Please advice.

Thanks,
Anil Pandilla

**Comment by zhangyiatmicrosoft** [comment]
The provided code contains > 500 lines with sophisticated logic. 
Please make an isolated example on what does not work. Again the TS definition has <b>nothing</b> to do with run time behavior.

The following code shows that loading clustered pushipin works fine with aerial mode:
```javascript
            var map = new Microsoft.Maps.Map(document.getElementById('myMap'), {
                center: new Microsoft.Maps.Location(47.601511, -122.326033),
                zoom: 12
            });
            Microsoft.Maps.loadModule('Microsoft.Maps.Clustering', { callback: clusterLoaded });

            function clusterLoaded()
            {
                // Creating sample Pushpin data within map view
                var pushpins = Microsoft.Maps.TestDataGenerator.getPushpins(1000, map.getBounds());
                var clusterLayer = new Microsoft.Maps.ClusterLayer(pushpins, { gridSize: 100 });
                map.layers.insert(clusterLayer);
                map.setView(
                    {
                        mapTypeId: Microsoft.Maps.MapTypeId.aerial,
                    });
            }
```
You may copy-paste the code above to our ISDK example and run directly:
https://www.bing.com/api/maps/sdk/mapcontrol/isdk/clusteringmeanaverage

**Comment by zhangyiatmicrosoft** [comment]
Closing the issue due to lack of response.
Please provide the requested information if you still have this problem.
