### ISSUE TITLE
DefinitelyTyped/bingmaps

### ISSUE THREAD

**Issue by payson** [Microsoft/Bing-Maps-V8-TypeScript-Definitions#5]
Hi, is the type definition here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/bingmaps for Bing Maps V8?
If not, is it possible for you to add one for V8?

**Comment by rbrundritt** [comment]
Those are for V7. V8 definitions are not currently available through definitely typed. Working with our legal team to ensure that there are no issues. Microsoft has strict policies around open source that we have to follow.

**Comment by rbrundritt** [comment]
Don't think definitely typed is needed now. These definitions are not available as both a nugget package and through npm.

**Comment by panuruj** [comment]
With more tooling around DefinitelyTyped and VSCode, @rbrundritt, can you please consider adding these types and publish them under @types? Following the convention massively helps with the productivity.

**Comment by ChibiBlasphem** [comment]
Hello @rbrundritt , we already passed the deprecated date of the v7.
Can you please migrate your typings for the v8 on DefinitelyTyped?
Thank you in advance

**Comment by rbrundritt** [comment]
The typings on DefinitelyTyped were not added by Microsoft. I'll look into what needs to be done to get these updated to V8.

**Comment by rbrundritt** [comment]
I've made a pull request on the definitely types repo including the latest definitions.

**Comment by rbrundritt** [comment]
After some modifications to the definitions to align with how they used to work in DefinitelyTyped, they are now passing all tests and the pull request is waiting to be merged.
