### ISSUE TITLE
Typings issue with geocoding request callback

### ISSUE THREAD

**Issue by Lumilele** [Microsoft/Bing-Maps-V8-TypeScript-Definitions#6]
Hi,

I have a problem with typings when I use the geocoding callback types.

        var mapControl = new Microsoft.Maps.Map(document.getElementById('bingMapContainer'), {
            credentials: 'some_key'
        });

        Microsoft.Maps.loadModule('Microsoft.Maps.Search', () => {
            var searchManager = new Microsoft.Maps.Search.SearchManager(mapControl);
            searchManager.geocode({
                bounds: mapControl.getBounds(),
                where: 'somewhere',
                callback: (answer, userData) => {
                    mapControl.setView({ bounds: answer.results[0].bestView });
                    mapControl.entities.push(new Microsoft.Maps.Pushpin(answer.results[0].location));
                }
            });
        });`

The IPlaceResult interface doesn't match what the Pushpin constructor is waiting for.
I have to replace the above code by this one to handle this.

`mapControl.entities.push(new Microsoft.Maps.Pushpin(answer.results[0].location as any));`

Kind regards and keep up the good work though !

**Comment by rbrundritt** [comment]
Yup, looks like there might have been some confusion due to the location property being an IGeocodeLocation object and there also being a locations property in V7/V8 which is an array of IGeocodeLocation objects. I'll fix this now. Thanks for reporting.
