### ISSUE TITLE
Unable to compile with noImplicitAny set to true

### ISSUE THREAD

**Issue by kb3eua** [Microsoft/Bing-Maps-V8-TypeScript-Definitions#7]
When I try to compile with these definitions, I get the following errors:
```
ERROR in [default] C:/Projects/BingTest/typings/globals/Directions/index.d.ts:484:15 
'clearDisplay', which lacks return-type annotation, implicitly has an 'any' return type.
ERROR in [default] C:/Projects/BingTest/typings/globals/Directions/index.d.ts:487:15 
'dispose', which lacks return-type annotation, implicitly has an 'any' return type.
ERROR in [default] C:/Projects/BingTest/typings/globals/Microsoft.Maps/index.d.ts:970:15 
'clear', which lacks return-type annotation, implicitly has an 'any' return type.
```
This is because in my tsconfig.json file I've set:
```
{
  "compilerOptions": {
    "noImplicitAny": true
  }
}
```
If I set **noImplicitAny** to _false_ then it compiles, but that's not what I want to use for my project.

**Comment by rbrundritt** [comment]
Thanks for reporting. The return type for all of these are void. I have updated the definitions and checked them in. Going to hold off updating the NuGet and npm packages until there is a few more updates.

**Comment by rbrundritt** [comment]
The npm and Nuget packages have been updated along with a number of other fixes.
